---
title: "ALCL TME signature depending on cells morphology"
date: '`r Sys.Date()`'
output:
    html_notebook:
    fig_height: 12
    fig_width: 10
    toc: yes
    toc_depth: 3
    toc_float: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}

library(devtools)
library(ggplot2)
library(RColorBrewer)
library(tidyr)
library(viridis)
library(pheatmap)
library(ConsensusClusterPlus)
library(ComplexHeatmap)
library(circlize)
library(ggpubr)
```


# ALCL depending on morphology

## 1. Functions & Metadata

```{r, warning = FALSE}

# useful functions

hcopt <- function(d, HC=NULL, method = "ward.D", members = NULL){
  require("cba")
  if ( is.null(HC) ) {
    HC <- hclust(d,method=method,members=members)
  }
  #optimal leaf ordering
  ORD <- cba::order.optimal(d,merge=HC$merge)
  HC$merge <- ORD$merge
  HC$order <- ORD$order
  HC
}

colGradient <- function( cols, length, cmax=255 )
{
  ## e.g., to create a white-to-red gradient with 10 levels
  ##   colGradient(cols=c('white','red'),length=10)
  ## or, to create a blue-to-white-to-red gradients with 9 colors
  ##   colGradient(cols=c('blue','white','red'),length=9)
  ramp <- grDevices::colorRamp(cols)
  rgb( ramp(seq(0,1,length=length)), max=cmax )
}

# metadata

metadata <- read.table(file = "./cel-affymetrix_ALCL_metadata.csv", header = TRUE)
metadata <- metadata[which(metadata$relapse!="NA" | metadata$morpho!="NA" ),]
metadata <- metadata[order(metadata$name),]
#metadata$relapse <- as.factor(metadata$relapse)
#metadata$morpho <- as.factor(metadata$morpho)
head(metadata)
dim(metadata)
```

## 2. CIBERSORT (online) with LM22 matrix + 2 stromal cell types from MCP-Counter on Affy expression data

```{r, warning = FALSE}

TME_estim <- as.matrix(read.table(file = "./CIBERSORTx-LM22_and_MCP-counter-stroma_Affy-ALCL-oPTCL_patients.csv", header = TRUE, row.names = 1))
TME_estim <- TME_estim[which(rownames(TME_estim)%in%metadata$name),]
data <- t(scale(as.matrix(TME_estim[,1:24])))
dim(data)
```

## 3. Graphical overviews 

### 3.1. Graphical overview of ALCL (Heatmap Supplementary Fig. 2)

```{r, warning = FALSE, fig.width=12, fig.height=14}

# we first remove the T cells memory activated and T cells CD8 cell types that can contain both normal and cancer T cells
TME_estim_short <- TME_estim[,which(!colnames(TME_estim)%in%c("T_cells_CD4_memory_activated","T_cells_CD8"))]

# create a dataframe for ggplot2 figures
d <- as.data.frame(cbind(sample=rownames(TME_estim_short),TME_estim_short[,1:22])) %>% 
gather(key = "cell_type", value = "score", 2:23, na.rm = TRUE, factor_key=TRUE)
d$score <- as.numeric(d$score)
d_metadat <- cbind(cbind(cbind(pathology=rep(metadata$pathology,22),relapse=rep(metadata$relapse,22)),morpho=rep(metadata$morpho,22)),d)
d_metadat$sample <- factor(d_metadat$sample, levels = unique(d_metadat$sample))
# scaled data (Z-score) and transposed
data <- t(scale(as.matrix(TME_estim_short[,1:22])))
dim(data)

# clustering / k choice
CCout <- ConsensusClusterPlus(data,maxK=4,reps=500,pItem=0.9,pFeature=1,
                              innerLinkage="ward.D", finalLinkage="ward.D",
                              title="cc",clusterAlg="hc",distance="euclidean", plot=NULL)
summary(CCout)
## notice the use of a variable (rather then using 3 directly in the following commands)
nc <- 2  # variable for the following commands

# Heatmap parameters
annot1 <- data.frame("ALCL_type"=as.factor(metadata[,c("pathology")]),"relapse"=as.factor(metadata[,c("relapse")]), "morphology" = as.factor(metadata[,c("morpho")]), "cluster"=CCout[[nc]]$consensusClass)
annot1$cluster <- as.factor(annot1$cluster)
rownames(annot1) <- metadata$name
annotCol <- list(ALCL_type = c("ALCL-" = "#dfcfe6", "ALCL+" = "#805194"), relapse = c("R" = "#d14747", "NR" = "#5ea8d6"),  morphology = c("CT" = "#46b36e","nonCT" ="#e69443"),cluster = c("1" = "#d9969c", "2" = "#8dc9af")) # "3" = "#6e7fb5"

## use cluster tree from consensus clustering for column ordering in heatmap
clust.col <- CCout[[nc]]$consensusTree
## determine row ordering based on de-novo clustering
clust.row <- hcopt(as.dist(1-cor(t(data))),method="ward.D")

# Color range for the heatmap
col_fun <- colorRamp2(c(-5, 0, 5), c("blue", "white", "red")) # Z-score
# HeatmapAnnotation object for up annotations
ha <- HeatmapAnnotation(df = annot1, col = annotCol,
  annotation_name_side = "left",   # position du nom de l'annotation
  annotation_legend_param = list(title_position = "topcenter",  # légende au-dessus et centrée
    nrow = 1                      # online legend
  )
)
# Heatmap
ht <- Heatmap(
  data, name = "scaled score", # nom du colorbar
  col = col_fun, top_annotation = ha,
  cluster_rows = clust.row, cluster_columns = clust.col,
  show_row_names = TRUE, show_column_names = FALSE,
  row_names_gp = gpar(fontsize = 12),   # taille du texte pour les lignes
  column_names_gp = gpar(fontsize = 10), # taille du texte pour les colonnes (au cas où)
  column_split = 2,                     # couper les colonnes en 3 groupes
  heatmap_legend_param = list(title_position = "topcenter",
    legend_direction = "horizontal"    # orientation horizontale de la légende
  )
)
# 4. Dessiner avec la légende au-dessus
pdf("heatmap_ALCL_only.pdf", width = 10, height = 8)
draw(ht, heatmap_legend_side = "top", annotation_legend_side = "top")
dev.off()

```

## 4. Compute p-values for each cell type comparison (boxplots)

### 4.1. Graphical overview of ALCL for each cell type (Boxplot Fig. 2)

```{r, warning = FALSE}

d <- as.data.frame(cbind(sample=rownames(TME_estim_short),TME_estim_short[,1:22])) %>% 
gather(key = "cell_type", value = "score", 2:23, na.rm = TRUE, factor_key=TRUE)
d$score <- as.numeric(d$score)
d_metadat <- cbind(cbind(cbind(pathology=rep(metadata$pathology,22),relapse=rep(metadata$relapse,22)),morpho=rep(metadata$morpho,22)),d)
d_metadat$sample <- factor(d_metadat$sample, levels = unique(d_metadat$sample))

# compute p-values between ALCL relapsing or morphology groups for the different cell types
perform_wilcox_test <- function(d, metadata, group_var = "patho") {
  wilcox_pval <- c()
  cells <- unique(d$cell_type)
  for (c in cells) {
    # Extract lines corresponding to cell type c
    cell_data <- d[which(d$cell_type == c), ]
    # Extract regrouping var from metadata
    group_values <- metadata[[group_var]]
    # Create a tab with the regrouping var and the scores
    mat <- cbind(group = group_values, cell_data)
    mat <- mat[which(mat$group!="NA"),]
    # Delete groups with only one category
    if (length(unique(mat$group)) <= 1 || any(is.na(mat$group))) {
      wilcox_pval[c] <- NA
      next
    }
    # Wilcoxon
    pval <- tryCatch({
      wilcox.test(score ~ group, data = mat)$p.value
    }, error = function(e) NA)
    wilcox_pval[c] <- pval
  }
  # Corrected p-values
  p_corrected <- p.adjust(wilcox_pval, method = "hochberg", n = length(wilcox_pval))
  return(p_corrected)
}

# p-values between ALCL relapsing / non relapsing
p <- perform_wilcox_test(d, metadata, group_var="relapse")
# significative ?
p[which(p<0.1)]

# Boxplots 
type="Fibroblasts"
my_comparisons <- list( c("R", "NR"))
d_short <- d_metadat[which(d_metadat$cell_type==type),]
d_short <- d_short[which(d_short$relapse!="NA"),]
ggplot(d_short, aes(x=relapse, y=score, fill=relapse)) +  labs(title=type)+
geom_boxplot(outlier.colour="darkgrey",outlier.size=2) + scale_fill_manual(labels = c("NR", "R"), values=c("#5ea8d6", "#d14747")) + theme_bw(base_size = 20) + xlab("") + stat_compare_means(comparisons = my_comparisons, size=4)+scale_x_discrete(labels=c("NR","R")) + theme(legend.position="none")

# p-values between ALCL morpho CT vs nonCT / non relapsing
p <- perform_wilcox_test(d, metadata, group_var="morpho")
# significative
p[which(p<0.05)] #1^10-5

pdf("boxplot_fi2_mono.pdf", width = 10, height = 6)
type="Monocytes"
my_comparisons <- list( c("CT", "nonCT"))
d_short <- d_metadat[which(d_metadat$cell_type==type),]
d_short <- d_short[which(d_short$morpho!="NA"),]
ggplot(d_short, aes(x=morpho, y=score, fill=morpho)) + labs(title=type)+
geom_boxplot(outlier.colour="darkgrey",outlier.size=2)+ scale_fill_manual(name = "morphology", labels = c("CT", "nonCT"), values=c("#46b36e", "#e69443")) + theme_bw(base_size = 20) + xlab("") + theme(legend.position='none') + stat_compare_means(comparisons = my_comparisons, size=4)+ scale_x_discrete(labels=c("CT","nonCT"))
dev.off()
pdf("boxplot_fi2_macro.pdf", width = 10, height = 6)
type="Macrophages_M1"
my_comparisons <- list( c("CT", "nonCT"))
d_short <- d_metadat[which(d_metadat$cell_type==type),]
d_short <- d_short[which(d_short$morpho!="NA"),]
ggplot(d_short, aes(x=morpho, y=score, fill=morpho)) + labs(title=type)+
geom_boxplot(outlier.colour="darkgrey",outlier.size=2)+ scale_fill_manual(name = "morphology", labels = c("CT", "nonCT"), values=c("#46b36e", "#e69443")) + theme_bw(base_size = 20) + xlab("") + theme(legend.position='none') + stat_compare_means(comparisons = my_comparisons, size=4)+ scale_x_discrete(labels=c("CT","nonCT"))
dev.off()
type="Dendritic_cells_activated"
my_comparisons <- list( c("CT", "nonCT"))
d_short <- d_metadat[which(d_metadat$cell_type==type),]
d_short <- d_short[which(d_short$morpho!="NA"),]
ggplot(d_short, aes(x=morpho, y=score, fill=morpho)) + labs(title=type)+
geom_boxplot(outlier.colour="darkgrey",outlier.size=2)+ scale_fill_manual(name = "morphology", labels = c("CT", "nonCT"), values=c("#46b36e", "#e69443")) + theme_bw(base_size = 20) + xlab("") + theme(legend.position='none') + stat_compare_means(comparisons = my_comparisons, size=4)+ scale_x_discrete(labels=c("CT","nonCT"))

```
